
class URL:
	FIMFICTION	= 'http://www.fimfiction.net/'
	STATIC		= 'http://www.fimfiction-static.net/'
	AJAX		= FIMFICTION + 'ajax/'
	DOWNLOAD	= FIMFICTION + 'download_'
	SEARCH_BASE	= FIMFICTION + 'index.php?'
	API_BASE	= FIMFICTION + 'api/story.php?story='
	LOGIN		= AJAX + 'login.php'
	READLATER	= AJAX + 'add_read_it_later.php'
	FAVOURITE	= AJAX + 'add_favourite.php'
	READ		= AJAX + 'toggle_read.php'
	RATE		= AJAX + 'rate.php'
	STORY		= FIMFICTION + 'story/'
	DOWNLOAD_TXT	= DOWNLOAD + 'story.php?story='
	DOWNLOAD_HTML	= DOWNLOAD + 'story.php?html&story='
	DOWNLOAD_EPUB	= DOWNLOAD + 'epub.php?story='
	CHAPTER_TXT		= DOWNLOAD + 'chapter.php?chapter='
	CHAPTER_HTML	= DOWNLOAD + 'chapter.php?html&chapter='
	RSS_BASE		= FIMFICTION + 'rss/'
	RSS_FAVOURITE	= RSS_BASE + 'tracking.php?user='